/**
 * Hirobius Design System — Style Dictionary multi-format token emitter.
 *
 * STATUS: parallel / additive. This does NOT replace scripts/build-tokens.mjs
 * (still the source of truth for tokens.css, the TS bridge, dark mode, tenant
 * overlays, and composite expansion). This emitter graduates the
 * scripts/poc/style-dictionary-poc into a production multi-target generator for
 * the **scalar variable layer**, proving RFC #3 Tier 1 ("one source, many
 * targets"): CSS vars, SCSS, JS/ESM, JSON, and React Native — all from
 * hirobius.tokens.json.
 *
 * Parity strategy: token VALUES are formatted by build-tokens.mjs's canonical
 * `valueToCSS` (imported, not reimplemented), so every emitted value is
 * byte-identical to tokens.css for the covered subset. Style Dictionary owns
 * naming + per-platform file emission. scripts/tokens-sd/parity.mjs verifies
 * the CSS output equals the canonical generator LIVE (no frozen snapshot — the
 * POC's stale expected.css drift is designed out).
 *
 * SCOPE (covered): every scalar token across all four tiers — primitive,
 * semantic, component, role. Semantic/component/role aliases are preserved as
 * `var(--…)` (theme-aware); primitives resolve to raw values, matching
 * build-tokens.mjs exactly.
 *
 * DEFERRED (phase 2 — composite expansion + modes): typography, motion,
 * transition, elevation, and shadow composites; the `[data-theme="dark"]`
 * mode block; and the `[data-tenant]` overlays. These need composite/mode
 * machinery beyond a flat var map and are intentionally out of this emitter.
 *
 * Run:    node scripts/tokens-sd/build.mjs
 * Verify: node scripts/tokens-sd/parity.mjs   (pnpm check:tokens-sd)
 */

import StyleDictionary from 'style-dictionary';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { readFileSync, mkdtempSync, readFileSync as read, rmSync } from 'fs';
import { tmpdir } from 'os';
import { walkTokens, valueToCSS } from '../build-tokens.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '../..');

/** Composite / mode token types handled by build-tokens.mjs's expanders, not here. */
export const DEFERRED_TYPES = new Set([
  'typography',
  'motion',
  'transition',
  'elevation',
  'shadow',
]);

/** Read the canonical DTCG source. */
export function readRawTokens() {
  return JSON.parse(readFileSync(join(ROOT, 'hirobius.tokens.json'), 'utf8'));
}

/**
 * Compute the covered scalar var map the SAME way build-tokens.mjs builds the
 * :root layer: primitives resolve aliases, everything else preserves them as
 * var(). Returns an array of { path, name, value } descriptors.
 *
 * @param {object} rawTokens  full DTCG token tree
 * @param {boolean} resolveAll  force-resolve every alias to a raw value (React
 *                              Native target — no CSS var support)
 */
export function collectScalarTokens(rawTokens, { resolveAll = false } = {}) {
  const out = [];
  for (const { path, type, value } of walkTokens(rawTokens)) {
    if (DEFERRED_TYPES.has(type)) continue;
    const preserveAlias = resolveAll ? false : path[0] !== 'primitive';
    const css = valueToCSS(value, type, preserveAlias, rawTokens);
    if (css == null) continue;
    out.push({ path, name: path.join('-'), value: String(css) });
  }
  return out;
}

/** Set a nested value at `path` inside `obj`, creating intermediate objects. */
function setNested(obj, path, leaf) {
  let node = obj;
  for (let i = 0; i < path.length - 1; i++) {
    node[path[i]] ??= {};
    node = node[path[i]];
  }
  node[path.at(-1)] = leaf;
}

/** Build a Style Dictionary `tokens` tree from pre-computed scalar leaves. */
function toSdTree(scalarTokens) {
  const tree = {};
  for (const { path, value } of scalarTokens) setNested(tree, path, { value });
  return tree;
}

// ── Name transform: join path segments with '-', preserve camelCase ──────────
// Mirrors build-tokens.mjs `pathToCSSVar`: parts.join('-'), no kebab conversion.
const nameHdsPreserveCamel = {
  type: 'name',
  transform: (token) => token.path.join('-'),
};

// ── Format helpers ───────────────────────────────────────────────────────────
const cssFormat = (selector) => async ({ dictionary }) =>
  `${selector} {\n` +
  dictionary.allTokens.map((t) => `  --${t.name}: ${t.value};`).join('\n') +
  `\n}\n`;

const scssFormat = async ({ dictionary }) =>
  dictionary.allTokens.map((t) => `$${t.name}: ${t.value};`).join('\n') + '\n';

const jsonFlatFormat = async ({ dictionary }) =>
  JSON.stringify(
    Object.fromEntries(dictionary.allTokens.map((t) => [`--${t.name}`, t.value])),
    null,
    2,
  ) + '\n';

const nestedTreeFormat = (exportName) => async ({ dictionary }) => {
  const tree = {};
  for (const t of dictionary.allTokens) setNested(tree, t.path, t.value);
  return (
    `// Generated by scripts/tokens-sd — do not edit manually.\n` +
    `export const ${exportName} = ${JSON.stringify(tree, null, 2)} as const;\n` +
    `export default ${exportName};\n`
  );
};

/**
 * Run Style Dictionary for one token set and return the produced file strings
 * keyed by logical name. We capture output in-memory (no disk writes here) so
 * both build.mjs and parity.mjs can consume it.
 */
async function runSd(sdTree, formats) {
  const buildPath = mkdtempSync(join(tmpdir(), 'hds-sd-')) + '/';
  const sd = new StyleDictionary({
    tokens: sdTree,
    hooks: {
      transforms: { 'name/hds-preserve-camel': nameHdsPreserveCamel },
      formats: {
        'hds/css': cssFormat(':root'),
        'hds/scss': scssFormat,
        'hds/json': jsonFlatFormat,
        'hds/js': nestedTreeFormat('hdsTokens'),
        'hds/rn': nestedTreeFormat('hdsTokensNative'),
      },
    },
    platforms: {
      out: {
        buildPath,
        transforms: ['name/hds-preserve-camel'],
        files: formats.map((f) => ({ destination: f.key, format: f.format })),
      },
    },
    log: { verbosity: 'silent' },
  });

  await sd.buildAllPlatforms();
  const captured = {};
  for (const f of formats) captured[f.key] = read(buildPath + f.key, 'utf8');
  rmSync(buildPath, { recursive: true, force: true });
  return captured;
}

/**
 * Generate every target. Returns { 'tokens.vars.css', 'tokens.vars.scss',
 * 'tokens.json', 'tokens.js', 'tokens.native.js' } as strings.
 */
export async function generateAll(rawTokens = readRawTokens()) {
  const themeAware = toSdTree(collectScalarTokens(rawTokens));
  const resolved = toSdTree(collectScalarTokens(rawTokens, { resolveAll: true }));

  const themed = await runSd(themeAware, [
    { key: 'tokens.vars.css', format: 'hds/css' },
    { key: 'tokens.vars.scss', format: 'hds/scss' },
    { key: 'tokens.json', format: 'hds/json' },
    { key: 'tokens.js', format: 'hds/js' },
  ]);
  const native = await runSd(resolved, [{ key: 'tokens.native.js', format: 'hds/rn' }]);

  return { ...themed, ...native };
}

/** Convenience for parity: just the CSS string. */
export async function generateCss(rawTokens = readRawTokens()) {
  return (await generateAll(rawTokens))['tokens.vars.css'];
}
