import { defineConfig } from 'oxlint';

// anti-slop (vendored, tools/oxlint/anti-slop) runs ALONGSIDE ESLint, warn-first.
// Every rule is a warning; scripts/check-anti-slop.mjs fails when any per-file,
// per-rule count rises above tools/oxlint/anti-slop-baseline.json.
export default defineConfig({
  // Only the rules below count; oxlint's default correctness set is ESLint's job here.
  categories: { correctness: 'off' },
  ignorePatterns: [
    '.agent/**',
    '.agents/**',
    '.claude/**',
    '.codex/**',
    '.continue/**',
    '.cursor/**',
    '.gemini/**',
    '.opencode/**',
    '.pi/**',
    '.roo/**',
    '.windsurf/**',
    'tools/oxlint/anti-slop/**',
    'node_modules/**',
    'dist/**',
    'coverage/**',
    'storybook-static/**',
    'temp/**',
    '.ssr-cache/**',
    'docs-site/**',
    'preview/**',
    'public/**',
    'fixtures/**',
    'templates/**',
    'starter-kit/**',
    'upgrade/**',
    '**/*.d.ts',
    '**/*.generated.*',
  ],
  jsPlugins: [{ name: 'anti-slop', specifier: './tools/oxlint/anti-slop/index.ts' }],
  rules: {
    'oxc/no-accumulating-spread': 'warn',
    'anti-slop/no-array-filter-map': 'warn',
    'anti-slop/no-reduce-accumulator-copy': 'warn',
    'anti-slop/no-chained-type-assertions': 'warn',
    'anti-slop/no-conditional-empty-object-spread': 'warn',
    'anti-slop/no-known-value-widening': 'warn',
    'anti-slop/no-module-mocking': 'warn',
    'anti-slop/no-object-parameters': 'warn',
    'anti-slop/no-reflect-apply': 'warn',
    'anti-slop/no-reflect-get': 'warn',
    'anti-slop/no-runtime-typeof': 'warn',
    'anti-slop/no-shape-in-symbol-names': 'warn',
    'anti-slop/no-unknown-parameters': 'warn',
    'anti-slop/no-unknown-returns': 'warn',
    'anti-slop/no-unknown-type-aliases': 'warn',
    'anti-slop/no-unsafe-dictionary-type': 'warn',
    'anti-slop/no-widen-then-assert': 'warn',
    'anti-slop/require-readable-spacing': 'off',
    'anti-slop/require-safety-comment-for-type-assertion': 'warn',
  },
});
