// @vitest-environment node
/**
 * CONSUMING.md and docs/CONSUMING.md ship in the package `files`, so a consumer
 * reads them at the version they install. 0.20.0 removed the pattern-tier modules
 * from the root barrel (hds#389 R1): the docs must not place one of them in the
 * main barrel, and docs/CONSUMING.md's subpath table must name every subpath the
 * package exports, `/patterns` included.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(__dirname, '..');
const read = (file: string) => readFileSync(resolve(ROOT, file), 'utf8');

/** What `/patterns` exports and the root does not (generated by `pnpm codemod:names`). */
const patternsOnly = new Set<string>(
  JSON.parse(read('codemods/patterns-subpath.names.json')).names,
);

const PKG = '@hirobius/design-system';

describe('docs/CONSUMING.md subpath table', () => {
  it('has a row for every subpath package.json exports', () => {
    const doc = read('docs/CONSUMING.md');
    const subpaths = Object.keys(JSON.parse(read('package.json')).exports).filter(
      (k) => k !== '.' && k !== './package.json',
    );
    const missing = subpaths
      .map((k) => `${PKG}/${k.replace(/^\.\//, '')}`)
      .filter((spec) => !doc.includes(`| \`${spec}\``));
    expect(missing).toEqual([]);
  });
});

describe('CONSUMING docs after the 0.20.0 root removals', () => {
  for (const file of ['CONSUMING.md', 'docs/CONSUMING.md']) {
    it(`${file}: a paragraph that speaks of the main barrel or core names no /patterns-only component without its subpath`, () => {
      const offenders = read(file)
        .split(/\n\s*\n/)
        .filter((p) => /main barrel|\bcore `/i.test(p))
        .flatMap((p) =>
          [...p.matchAll(/`([A-Za-z]+)`/g)]
            .map((m) => m[1])
            .filter((name) => patternsOnly.has(name) && !p.includes(`${PKG}/patterns`))
            .map((name) => `${name}: ${p.slice(0, 80).replace(/\n/g, ' ')}`),
        );
      expect(offenders).toEqual([]);
    });
  }

  it('CONSUMING.md does not say the root barrel exports the pattern tier', () => {
    const rootRow = read('CONSUMING.md')
      .split('\n')
      .find((l) => l.startsWith(`| \`${PKG}\` `));
    expect(rootRow).toBeDefined();
    expect(rootRow).not.toMatch(/primitives, patterns/);
  });
});
