// @vitest-environment node
/**
 * CONSUMING.md and docs/CONSUMING.md ship in the package `files`, so a consumer
 * reads them at the version they install. 0.20.0 removed the pattern-tier modules
 * from the root barrel (hds#389 R1): the docs must not place one of them in the
 * main barrel, and docs/CONSUMING.md's subpath table must name every subpath the
 * package exports, `/patterns` included.
 */

import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { ONE_COMMAND, ONE_COMMAND_BIN, ONE_COMMAND_FROM } from '../scripts/upgrade/compile.mjs';
import { compareVersions } from '../scripts/upgrade/schema.mjs';

const ROOT = resolve(__dirname, '..');
const read = (file: string) => readFileSync(resolve(ROOT, file), 'utf8');

/** What `/patterns` exports and the root does not (generated by `pnpm codemod:names`). */
const patternsOnly = new Set<string>(
  JSON.parse(read('codemods/patterns-subpath.names.json')).names,
);

const PKG = '@hirobius/design-system';

describe('docs/CONSUMING.md subpath table', () => {
  it('has a row for every subpath package.json exports', () => {
    const doc = read('docs/CONSUMING.md');
    const subpaths = Object.keys(JSON.parse(read('package.json')).exports).filter(
      (k) => k !== '.' && k !== './package.json',
    );
    const missing = subpaths
      .map((k) => `${PKG}/${k.replace(/^\.\//, '')}`)
      .filter((spec) => !doc.includes(`| \`${spec}\``));
    expect(missing).toEqual([]);
  });
});

describe('CONSUMING docs after the 0.20.0 root removals', () => {
  for (const file of ['CONSUMING.md', 'docs/CONSUMING.md']) {
    it(`${file}: a paragraph that speaks of the main barrel or core names no /patterns-only component without its subpath`, () => {
      const offenders = read(file)
        .split(/\n\s*\n/)
        .filter((p) => /main barrel|\bcore `/i.test(p))
        .flatMap((p) =>
          [...p.matchAll(/`([A-Za-z]+)`/g)]
            .map((m) => m[1])
            .filter((name) => patternsOnly.has(name) && !p.includes(`${PKG}/patterns`))
            .map((name) => `${name}: ${p.slice(0, 80).replace(/\n/g, ' ')}`),
        );
      expect(offenders).toEqual([]);
    });
  }

  it('CONSUMING.md does not say the root barrel exports the pattern tier', () => {
    const rootRow = read('CONSUMING.md')
      .split('\n')
      .find((l) => l.startsWith(`| \`${PKG}\` `));
    expect(rootRow).toBeDefined();
    expect(rootRow).not.toMatch(/primitives, patterns/);
  });
});

// hds#451: `pnpm update` never crosses a 0.x minor, so the upgrade path is the
// exact version plus UPGRADING.md, and from 0.22.0 one command (hds#452).
describe('upgrading (hds#451)', () => {
  const section3 = () => {
    const doc = read('CONSUMING.md');
    const start = doc.indexOf('## 3. ');
    return doc.slice(start, doc.indexOf('\n## ', start + 1));
  };

  it('CONSUMING.md §3 shows the one command as coming in 0.22.0 and keeps the manual route for today', () => {
    const s3 = section3();
    expect(s3).toContain('npx @hirobius/design-system@latest upgrade');
    expect(s3).toMatch(/0\.22\.0/);
    expect(s3).toContain('](UPGRADING.md)');
    expect(s3).toContain(`pnpm add ${PKG}@`);
    expect(s3).not.toMatch(/pnpm update @hirobius\/design-system\s+#\s*latest/);
  });

  it('README links UPGRADING.md at the top', () => {
    const top = read('README.md').split('\n').slice(0, 15).join('\n');
    expect(top).toContain('](UPGRADING.md)');
  });

  // README and CONSUMING ship in the tarball, so "From 0.22.0, one command does
  // it" must not ship in a 0.22.0 that lacks the command: the Version PR runs
  // pnpm test, so this turns it red until hds#452 lands or the text changes.
  const docs = () => ({
    'README.md': read('README.md').split('\n').slice(0, 15).join('\n'),
    'CONSUMING.md': section3(),
  });

  it('names the one command from the release compile.mjs plans it for', () => {
    for (const [file, text] of Object.entries(docs())) {
      expect(promisedFrom(text), file).toEqual([ONE_COMMAND_FROM]);
    }
  });

  it('refuses a release that reaches that version without the design-system bin', () => {
    const at = (version: string, bin?: Record<string, string>) =>
      brokenPromise({ version, bin }, docs());
    expect(at('0.21.0')).toBeNull();
    expect(at(ONE_COMMAND_FROM)).toContain('hds#452');
    expect(at(ONE_COMMAND_FROM)).toContain('README.md');
    expect(at('0.23.1')).not.toBeNull();
    expect(at(ONE_COMMAND_FROM, { [ONE_COMMAND_BIN]: 'codemods/upgrade.mjs' })).toBeNull();
  });

  // Every shipped doc, not only the two that promise it: a bare mention in a
  // CHANGELOG entry or a MIGRATIONS guide promises the command just the same.
  it('refuses a shipped doc that names the one command with no release before it', () => {
    const at = (text: string, bin?: Record<string, string>) =>
      brokenPromise({ version: '0.21.0', bin }, { 'GUIDE.md': text });
    expect(at(`Run \`${ONE_COMMAND}\` to find each use.`)).toContain('GUIDE.md');
    expect(at(`From ${ONE_COMMAND_FROM}, \`${ONE_COMMAND}\` finds each use.`)).toBeNull();
    expect(
      at(`From ${ONE_COMMAND_FROM}, one command does it:\n\n\`\`\`sh\n${ONE_COMMAND}\n\`\`\``),
    ).toBeNull();
    expect(at(`In a later release, \`${ONE_COMMAND}\` fetches the newest steps.`)).toBeNull();
    expect(at(`Run \`${ONE_COMMAND}\`.`, { [ONE_COMMAND_BIN]: 'codemods/upgrade.mjs' })).toBeNull();
  });

  it('reads every Markdown and text file package.json#files ships, and README.md', () => {
    expect(Object.keys(shippedDocs())).toEqual(
      expect.arrayContaining([
        'README.md',
        'CONSUMING.md',
        'docs/CONSUMING.md',
        'UPGRADING.md',
        'MIGRATIONS.md',
        'CHANGELOG.md',
        'AGENTS.md',
        'llms.txt',
        'public/llms-full.txt',
      ]),
    );
  });

  it('holds for this package.json, in every shipped doc', () => {
    expect(brokenPromise(JSON.parse(read('package.json')), shippedDocs())).toBeNull();
  });
});

/** The versions `text` says the one command works from ("From 0.22.0, ..."). */
function promisedFrom(text: string): string[] {
  return [...text.matchAll(/\bFrom (\d+\.\d+\.\d+),/g)].map((m) => m[1]);
}

/**
 * Every Markdown and text file the package ships, by path: README.md (npm
 * always packs it) and each one package.json#files names or holds, but the
 * dist build.
 */
function shippedDocs(): Record<string, string> {
  const found = new Set<string>(['README.md']);
  const walk = (rel: string) => {
    const abs = resolve(ROOT, rel);
    if (!existsSync(abs)) return;
    if (statSync(abs).isDirectory()) {
      for (const name of readdirSync(abs)) walk(`${rel.replace(/\/$/, '')}/${name}`);
    } else if (/\.(?:md|txt)$/.test(rel)) found.add(rel);
  };
  for (const entry of JSON.parse(read('package.json')).files as string[]) {
    if (entry !== 'dist') walk(entry);
  }
  return Object.fromEntries([...found].sort().map((file) => [file, read(file)]));
}

/**
 * Why `docs` promise a command the package lacks, or null. Without the
 * design-system bin, each paragraph naming the one command, or the paragraph
 * before it (a code block's lead-in), must say which release brings it
 * ("From 0.22.0," or "In a later release"), and `pkg` must not have reached
 * that release.
 */
function brokenPromise(
  pkg: { version: string; bin?: Record<string, string> },
  docs: Record<string, string>,
): string | null {
  if (Object.hasOwn(pkg.bin ?? {}, ONE_COMMAND_BIN)) return null;
  const fix = `land hds#452 (the bin) before this release, or reword it and ONE_COMMAND_FROM in scripts/upgrade/compile.mjs`;
  for (const [file, text] of Object.entries(docs)) {
    const blocks = text.split(/\n\s*\n/);
    for (const [i, block] of blocks.entries()) {
      if (!block.includes(ONE_COMMAND)) continue;
      const near = `${blocks[i - 1] ?? ''}\n\n${block}`;
      if (/\bIn a later release\b/.test(near)) continue;
      const from = promisedFrom(near);
      if (from.length === 0) {
        return `${file} names \`${ONE_COMMAND}\` with no "From <version>," before it, but package.json is at ${pkg.version} with no ${ONE_COMMAND_BIN} bin: say "From ${ONE_COMMAND_FROM}, ..." there, or ${fix}. It reads: ${block.slice(0, 100)}`;
      }
      const reached = from.find((v) => compareVersions(pkg.version, v) >= 0);
      if (reached) {
        return `${file} says \`${ONE_COMMAND}\` works from ${reached}, but package.json is at ${pkg.version} with no ${ONE_COMMAND_BIN} bin: ${fix}.`;
      }
    }
  }
  return null;
}
