// @vitest-environment node
/**
 * CONSUMING.md and docs/CONSUMING.md ship in the package `files`, so a consumer
 * reads them at the version they install. 0.20.0 removed the pattern-tier modules
 * from the root barrel (hds#389 R1): the docs must not place one of them in the
 * main barrel, and docs/CONSUMING.md's subpath table must name every subpath the
 * package exports, `/patterns` included.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ONE_COMMAND, ONE_COMMAND_BIN, ONE_COMMAND_FROM } from '../scripts/upgrade/compile.mjs';
import { compareVersions } from '../scripts/upgrade/schema.mjs';

const ROOT = resolve(__dirname, '..');
const read = (file: string) => readFileSync(resolve(ROOT, file), 'utf8');

/** What `/patterns` exports and the root does not (generated by `pnpm codemod:names`). */
const patternsOnly = new Set<string>(
  JSON.parse(read('codemods/patterns-subpath.names.json')).names,
);

const PKG = '@hirobius/design-system';

describe('docs/CONSUMING.md subpath table', () => {
  it('has a row for every subpath package.json exports', () => {
    const doc = read('docs/CONSUMING.md');
    const subpaths = Object.keys(JSON.parse(read('package.json')).exports).filter(
      (k) => k !== '.' && k !== './package.json',
    );
    const missing = subpaths
      .map((k) => `${PKG}/${k.replace(/^\.\//, '')}`)
      .filter((spec) => !doc.includes(`| \`${spec}\``));
    expect(missing).toEqual([]);
  });
});

describe('CONSUMING docs after the 0.20.0 root removals', () => {
  for (const file of ['CONSUMING.md', 'docs/CONSUMING.md']) {
    it(`${file}: a paragraph that speaks of the main barrel or core names no /patterns-only component without its subpath`, () => {
      const offenders = read(file)
        .split(/\n\s*\n/)
        .filter((p) => /main barrel|\bcore `/i.test(p))
        .flatMap((p) =>
          [...p.matchAll(/`([A-Za-z]+)`/g)]
            .map((m) => m[1])
            .filter((name) => patternsOnly.has(name) && !p.includes(`${PKG}/patterns`))
            .map((name) => `${name}: ${p.slice(0, 80).replace(/\n/g, ' ')}`),
        );
      expect(offenders).toEqual([]);
    });
  }

  it('CONSUMING.md does not say the root barrel exports the pattern tier', () => {
    const rootRow = read('CONSUMING.md')
      .split('\n')
      .find((l) => l.startsWith(`| \`${PKG}\` `));
    expect(rootRow).toBeDefined();
    expect(rootRow).not.toMatch(/primitives, patterns/);
  });
});

// hds#451: `pnpm update` never crosses a 0.x minor, so the upgrade path is the
// exact version plus UPGRADING.md, and from 0.22.0 one command (hds#452).
describe('upgrading (hds#451)', () => {
  const section3 = () => {
    const doc = read('CONSUMING.md');
    const start = doc.indexOf('## 3. ');
    return doc.slice(start, doc.indexOf('\n## ', start + 1));
  };

  it('CONSUMING.md §3 shows the one command as coming in 0.22.0 and keeps the manual route for today', () => {
    const s3 = section3();
    expect(s3).toContain('npx @hirobius/design-system@latest upgrade');
    expect(s3).toMatch(/0\.22\.0/);
    expect(s3).toContain('](UPGRADING.md)');
    expect(s3).toContain(`pnpm add ${PKG}@`);
    expect(s3).not.toMatch(/pnpm update @hirobius\/design-system\s+#\s*latest/);
  });

  it('README links UPGRADING.md at the top', () => {
    const top = read('README.md').split('\n').slice(0, 15).join('\n');
    expect(top).toContain('](UPGRADING.md)');
  });

  // README and CONSUMING ship in the tarball, so "From 0.22.0, one command does
  // it" must not ship in a 0.22.0 that lacks the command: the Version PR runs
  // pnpm test, so this turns it red until hds#452 lands or the text changes.
  const docs = () => ({
    'README.md': read('README.md').split('\n').slice(0, 15).join('\n'),
    'CONSUMING.md': section3(),
  });

  it('names the one command from the release compile.mjs plans it for', () => {
    for (const [file, text] of Object.entries(docs())) {
      expect(promisedFrom(text), file).toEqual([ONE_COMMAND_FROM]);
    }
  });

  it('refuses a release that reaches that version without the design-system bin', () => {
    const at = (version: string, bin?: Record<string, string>) =>
      brokenPromise({ version, bin }, docs());
    expect(at('0.21.0')).toBeNull();
    expect(at(ONE_COMMAND_FROM)).toContain('hds#452');
    expect(at(ONE_COMMAND_FROM)).toContain('README.md');
    expect(at('0.23.1')).not.toBeNull();
    expect(at(ONE_COMMAND_FROM, { [ONE_COMMAND_BIN]: 'codemods/upgrade.mjs' })).toBeNull();
  });

  it('holds for this package.json', () => {
    expect(brokenPromise(JSON.parse(read('package.json')), docs())).toBeNull();
  });
});

/** The versions `text` says the one command works from ("From 0.22.0, ..."). */
function promisedFrom(text: string): string[] {
  return [...text.matchAll(/\bFrom (\d+\.\d+\.\d+),/g)].map((m) => m[1]);
}

/**
 * Why `docs` promise a command the package lacks, or null: they say the one
 * command works from a version `pkg` has reached, and its bin has no
 * design-system yet.
 */
function brokenPromise(
  pkg: { version: string; bin?: Record<string, string> },
  docs: Record<string, string>,
): string | null {
  if (Object.hasOwn(pkg.bin ?? {}, ONE_COMMAND_BIN)) return null;
  for (const [file, text] of Object.entries(docs)) {
    const from = promisedFrom(text).find((v) => compareVersions(pkg.version, v) >= 0);
    if (from) {
      return `${file} says \`${ONE_COMMAND}\` works from ${from}, but package.json is at ${pkg.version} with no ${ONE_COMMAND_BIN} bin: land hds#452 (the bin) before this release, or reword ${file} and ONE_COMMAND_FROM in scripts/upgrade/compile.mjs.`;
    }
  }
  return null;
}
