// url=https://www.figma.com/design/FIXTUREKEY/Fixture?node-id=1-2
// source=src/app/components/widget.tsx
// component=Widget
//
// GENERATED by scripts/generate-code-connect.mjs from figma/code-connect.json
// (Figma properties, evidence: fixture) and the cva variants in the source.
// Do not edit by hand: change the registry or the component, then regenerate.
import figma from 'figma';

const instance = figma.selectedInstance;

const tone = instance.getEnum('Tone', {
  info: 'info',
  danger: 'danger',
});

export default {
  example: figma.code`<Widget${tone === 'info' ? '' : ` tone="${tone}"`} />`,
  imports: ["import { Widget } from '@hirobius/design-system'"],
  id: 'widget',
  metadata: { nestable: true },
};
