// url=https://www.figma.com/design/c8MaVgwxOlxm4wr8wnH0Z4/HDS-Tokens-Components?node-id=33-34
// source=src/app/components/alert.tsx
// component=Alert
//
// GENERATED by scripts/generate-code-connect.mjs from figma/code-connect.json
// (Figma properties, evidence: hds#73) and the cva variants in the source.
// Do not edit by hand: change the registry or the component, then regenerate.
import figma from 'figma';

const instance = figma.selectedInstance;

const tone = instance.getEnum('Tone', {
  info: 'info',
  success: 'success',
  warning: 'warning',
  danger: 'danger',
});
const showTitle = instance.getBoolean('Show title');
const title = instance.getString('Title');
const body = instance.getString('Body');

export default {
  example: figma.code`<Alert${tone === 'info' ? '' : ` tone="${tone}"`}${showTitle ? ` title="${title}"` : ''}>${body}</Alert>`,
  imports: ["import { Alert } from '@hirobius/design-system'"],
  id: 'alert',
  metadata: { nestable: true },
};
