// url=https://www.figma.com/design/c8MaVgwxOlxm4wr8wnH0Z4/HDS-Tokens-Components?node-id=34-18
// source=src/app/components/avatar.tsx
// component=Avatar
//
// GENERATED by scripts/generate-code-connect.mjs from figma/code-connect.json
// (Figma properties, evidence: hds#73) and the cva variants in the source.
// Do not edit by hand: change the registry or the component, then regenerate.
import figma from 'figma';

const instance = figma.selectedInstance;

const size = instance.getEnum('Size', {
  sm: 'sm',
  md: 'md',
  lg: 'lg',
});
const type = instance.getEnum('Type', {
  Initials: 'Initials',
  Image: 'Image',
});
const initials = instance.getString('Initials');

export default {
  example: figma.code`<Avatar${size === 'md' ? '' : ` size="${size}"`}${type === 'Image' ? ' src={user.avatarUrl}' : ''} initials="${initials}" alt={user.name} />`,
  imports: ["import { Avatar } from '@hirobius/design-system'"],
  id: 'avatar',
  metadata: { nestable: true },
};
