// url=https://www.figma.com/design/c8MaVgwxOlxm4wr8wnH0Z4/HDS-Tokens-Components?node-id=31-15
// source=src/app/components/badge.tsx
// component=Badge
//
// GENERATED by scripts/generate-code-connect.mjs from figma/code-connect.json
// (Figma properties, evidence: hds#73) and the cva variants in the source.
// Do not edit by hand: change the registry or the component, then regenerate.
import figma from 'figma';

const instance = figma.selectedInstance;

const tone = instance.getEnum('Tone', {
  neutral: 'neutral',
  info: 'info',
  success: 'success',
  danger: 'danger',
  warning: 'warning',
  inProgress: 'inProgress',
});
const label = instance.getString('Label');

export default {
  example: figma.code`<Badge${tone === 'neutral' ? '' : ` tone="${tone}"`}>${label}</Badge>`,
  imports: ["import { Badge } from '@hirobius/design-system'"],
  id: 'badge',
  metadata: { nestable: true },
};
