// url=https://www.figma.com/design/c8MaVgwxOlxm4wr8wnH0Z4/HDS-Tokens-Components?node-id=28-138
// source=src/app/components/button.tsx
// component=Button
//
// GENERATED by scripts/generate-code-connect.mjs from figma/code-connect.json
// (Figma properties, evidence: hds#73) and the cva variants in the source.
// Do not edit by hand: change the registry or the component, then regenerate.
import figma from 'figma';

const instance = figma.selectedInstance;

const variant = instance.getEnum('Variant', {
  Primary: 'primary',
  Secondary: 'secondary',
  Tertiary: 'tertiary',
});
const tone = instance.getEnum('Tone', {
  neutral: 'neutral',
  danger: 'danger',
  success: 'success',
  warning: 'warning',
  info: 'info',
});
const size = instance.getEnum('Size', {
  sm: 'sm',
  md: 'md',
  lg: 'lg',
});
const state = instance.getEnum('State', {
  Default: 'Default',
  Hover: 'Hover',
  Disabled: 'Disabled',
  Loading: 'Loading',
});
const label = instance.getString('Label');
const showIcon = instance.getBoolean('Show icon');
const showTrailIcon = instance.getBoolean('Show trail icon');
const icon = showIcon ? instance.getInstanceSwap('Icon') : undefined;
const iconCode = icon && icon.type === 'INSTANCE' ? icon.executeTemplate().example : undefined;
const trailIcon = showTrailIcon ? instance.getInstanceSwap('Trail Icon') : undefined;
const trailIconCode =
  trailIcon && trailIcon.type === 'INSTANCE' ? trailIcon.executeTemplate().example : undefined;

export default {
  example: figma.code`<Button${variant === 'secondary' ? '' : ` variant="${variant}"`}${tone === 'neutral' ? '' : ` tone="${tone}"`}${size === 'md' ? '' : ` size="${size}"`}${state === 'Disabled' ? ' disabled' : ''}${state === 'Loading' ? ' loading' : ''}${iconCode ? figma.code` iconLeft={${iconCode}}` : ''}${trailIconCode ? figma.code` iconRight={${trailIconCode}}` : ''}>${label}</Button>`,
  imports: ["import { Button } from '@hirobius/design-system'"],
  id: 'button',
  metadata: { nestable: true },
};
