// url=https://www.figma.com/design/c8MaVgwxOlxm4wr8wnH0Z4/HDS-Tokens-Components?node-id=35-29
// source=src/app/components/checkbox.tsx
// component=Checkbox
//
// GENERATED by scripts/generate-code-connect.mjs from figma/code-connect.json
// (Figma properties, evidence: hds#73) and the cva variants in the source.
// Do not edit by hand: change the registry or the component, then regenerate.
import figma from 'figma';

const instance = figma.selectedInstance;

const label = instance.getString('Label');
const state = instance.getEnum('State', {
  unchecked: 'unchecked',
  checked: 'checked',
  indeterminate: 'indeterminate',
});
const disabled = instance.getEnum('Disabled', {
  false: 'false',
  true: 'true',
});

export default {
  example: figma.code`<Checkbox label="${label}"${state === 'unchecked' || state === 'indeterminate' ? ' checked={false}' : state === 'checked' ? ' checked' : ''}${state === 'indeterminate' ? ' indeterminate' : ''}${disabled === 'true' ? ' disabled' : ''} onChange={setChecked} />`,
  imports: ["import { Checkbox } from '@hirobius/design-system'"],
  id: 'checkbox',
  metadata: { nestable: true },
};
