// url=https://www.figma.com/design/UNMAPPED/HdsCheckbox
// source=src/app/components/checkbox.tsx
// component=HdsCheckbox
//
// UNMAPPED: no Figma node URL is recorded for HdsCheckbox. Add `@figma <node-url>` to the
// component JSDoc in src/app/components/checkbox.tsx, then run `pnpm figma:connect:generate`.
// `pnpm figma:connect:check` lists every unmapped template.
//
// GENERATED by scripts/generate-code-connect.mjs from figma/code-connect.json
// (Figma properties, evidence: hds#73) and the cva variants in the source.
// Do not edit by hand: change the registry or the component, then regenerate.
import figma from 'figma';

const instance = figma.selectedInstance;

const label = instance.getString('Label');
const state = instance.getEnum('State', {
  unchecked: 'unchecked',
  checked: 'checked',
  indeterminate: 'indeterminate',
});
const disabled = instance.getEnum('Disabled', {
  false: 'false',
  true: 'true',
});

export default {
  example: figma.code`<HdsCheckbox label="${label}"${state === 'unchecked' || state === 'indeterminate' ? ' checked={false}' : state === 'checked' ? ' checked' : ''}${state === 'indeterminate' ? ' indeterminate' : ''}${disabled === 'true' ? ' disabled' : ''} onChange={setChecked} />`,
  imports: ["import { HdsCheckbox } from '@hirobius/design-system'"],
  id: 'hds-checkbox',
  metadata: { nestable: true },
};
