// url=https://www.figma.com/design/c8MaVgwxOlxm4wr8wnH0Z4/HDS-Tokens-Components?node-id=38-20
// source=src/app/components/input.tsx
// component=Input
//
// GENERATED by scripts/generate-code-connect.mjs from figma/code-connect.json
// (Figma properties, evidence: hds#73) and the cva variants in the source.
// Do not edit by hand: change the registry or the component, then regenerate.
import figma from 'figma';

const instance = figma.selectedInstance;

const state = instance.getEnum('State', {
  Default: 'Default',
  Focus: 'Focus',
  Error: 'Error',
  Disabled: 'Disabled',
});
const size = instance.getEnum('Size', {
  lg: 'lg',
  sm: 'sm',
  md: 'md',
});
const showLabel = instance.getBoolean('Show label');
const label = instance.getString('Label');
const value = instance.getString('Value');

export default {
  example: figma.code`<Input${state === 'Error' ? ' error' : ''}${state === 'Disabled' ? ' disabled' : ''}${size === 'md' ? '' : ` size="${size}"`}${showLabel ? ` label="${label}"` : ''} defaultValue="${value}" />`,
  imports: ["import { Input } from '@hirobius/design-system'"],
  id: 'input',
  metadata: { nestable: true },
};
