// url=https://www.figma.com/design/2VgBbVpKiDnu0aftJEVyBQ/HDS-Tokens-Components?node-id=36-17
// source=src/app/components/radio.tsx
// component=Radio
//
// GENERATED by scripts/generate-code-connect.mjs from figma/code-connect.json
// (Figma properties, evidence: hds#73) and the cva variants in the source.
// Do not edit by hand: change the registry or the component, then regenerate.
import figma from 'figma';

const instance = figma.selectedInstance;

const label = instance.getString('Label');
const checked = instance.getEnum('Checked', {
  false: 'false',
  true: 'true',
});
const disabled = instance.getEnum('Disabled', {
  false: 'false',
  true: 'true',
});

export default {
  example: figma.code`<Radio label="${label}"${checked === 'false' ? ' checked={false}' : checked === 'true' ? ' checked' : ''}${disabled === 'true' ? ' disabled' : ''} onChange={setChecked} />`,
  imports: ["import { Radio } from '@hirobius/design-system'"],
  id: 'radio',
  metadata: { nestable: true },
};
