// url=https://www.figma.com/design/c8MaVgwxOlxm4wr8wnH0Z4/HDS-Tokens-Components?node-id=32-11
// source=src/app/components/tag.tsx
// component=Tag
//
// GENERATED by scripts/generate-code-connect.mjs from figma/code-connect.json
// (Figma properties, evidence: hds#73) and the cva variants in the source.
// Do not edit by hand: change the registry or the component, then regenerate.
import figma from 'figma';

const instance = figma.selectedInstance;

const active = instance.getEnum('Active', {
  false: 'false',
  true: 'true',
});
const label = instance.getString('Label');

export default {
  example: figma.code`<Tag${active === 'true' ? ' active' : ''}>${label}</Tag>`,
  imports: ["import { Tag } from '@hirobius/design-system'"],
  id: 'tag',
  metadata: { nestable: true },
};
