/** @internal — not part of @hirobius/design-system public API surface. */
/**
 * Hirobius Design System — design ↔ code links (readiness plan A8).
 *
 * One source: `componentSpecs[<Name>].figmaUrl` in public/hds-manifest.json,
 * which `pnpm manifest:generate` fills from the component's `@figma` JSDoc tag.
 * Everything here is a projection of it, and works on any Figma plan:
 *   - the README "Design ↔ Code links" section (renderReadmeSection);
 *   - Storybook `parameters.design`, through src/stories/design-parameters.ts
 *     (collectDesignLinks reports a story that does not use it, or that
 *     hardcodes a Figma URL);
 *   - Figma dev resources on each node, through the REST API
 *     (planDevResources, syncDevResources: needs a token, run by a person);
 *   - Figma component descriptions and documentation links, through a
 *     use_figma script (buildDescriptionsScript: the REST API cannot write them).
 * Nothing here reads a token or talks to Figma unless syncDevResources is called.
 */

import ts from 'typescript';
import { hdsChecksum } from './figma-runtime.mjs';

export const DESIGN_LINKS_START =
  '<!-- design-links:start (generated by `pnpm figma:links`; edit the @figma JSDoc tag, not this section) -->';
export const DESIGN_LINKS_END = '<!-- design-links:end -->';
const START_PREFIX = '<!-- design-links:start';
const README_ANCHOR = '\n## Visual direction';

const DEV_RESOURCE_NAMES = { source: 'HDS source', story: 'HDS story' };
const FIGMA_URL_IN_TEXT = /https?:\/\/(www\.)?figma\.com\//;

// ── Figma node URLs ──────────────────────────────────────────────────────────
/**
 * The file key and node id of a Figma node URL, or null for anything else
 * (placeholders, file links without a node, other hosts, instance sublayers).
 *
 * @param {unknown} url
 * @returns {{ fileKey: string, nodeId: string } | null}
 */
export function parseFigmaNodeUrl(url) {
  if (typeof url !== 'string') return null;
  let parsed;
  try {
    parsed = new URL(url);
  } catch {
    return null;
  }
  if (parsed.protocol !== 'https:' || !['figma.com', 'www.figma.com'].includes(parsed.hostname)) {
    return null;
  }
  const path = parsed.pathname.match(/^\/(?:design|file|proto)\/([A-Za-z0-9]+)(?:\/|$)/);
  const nodeId = (parsed.searchParams.get('node-id') ?? '').replace('-', ':');
  if (!path || !/^\d+:\d+$/.test(nodeId)) return null;
  return { fileKey: path[1], nodeId };
}

// ── Stories ──────────────────────────────────────────────────────────────────
/** Storybook's id sanitizer (@storybook/csf `sanitize`). */
const sanitize = (text) =>
  text
    .toLowerCase()
    .replace(/[ ’–—―′¿'`~!@#$%^&*()_|+\-=?;:'",.<>{}[\]\\/]/gi, '-')
    .replace(/-+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '');

/** Storybook's story name for an export (lodash startCase, as @storybook/csf uses). */
const storyNameFromExport = (key) =>
  key
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .replace(/([A-Za-z])(\d)/g, '$1 $2')
    .replace(/[_-]+/g, ' ')
    .trim();

/** The Storybook docs page id for a meta title (autodocs). */
export const storyDocsId = (title) => `${sanitize(title)}--docs`;

const unwrap = (node) => {
  let current = node;
  while (
    current &&
    (ts.isSatisfiesExpression(current) ||
      ts.isAsExpression(current) ||
      ts.isParenthesizedExpression(current))
  ) {
    current = current.expression;
  }
  return current;
};

/**
 * What a CSF story file declares about itself, read from its syntax tree.
 *
 * @param {string} source  A *.stories.tsx file.
 * @returns {{ title: string|null, component: string|null, tags: string[], firstStory: string|null, designParameters: string[], figmaUrlLiterals: number } | null}
 *   null when the file default-exports no object meta.
 */
export function readStoryMeta(source) {
  const file = ts.createSourceFile(
    'story.tsx',
    source,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TSX,
  );
  const consts = new Map();
  const exported = [];
  let meta = null;
  for (const statement of file.statements) {
    if (ts.isVariableStatement(statement)) {
      const isExported = statement.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
      for (const declaration of statement.declarationList.declarations) {
        if (!ts.isIdentifier(declaration.name) || !declaration.initializer) continue;
        consts.set(declaration.name.text, unwrap(declaration.initializer));
        if (isExported) exported.push(declaration.name.text);
      }
    } else if (ts.isExportAssignment(statement) && !statement.isExportEquals) {
      meta = unwrap(statement.expression);
      if (meta && ts.isIdentifier(meta)) {
        const name = meta.text;
        meta = consts.get(name);
        if (exported.includes(name)) exported.splice(exported.indexOf(name), 1); // the meta is not a story
      }
    }
  }
  if (!meta || !ts.isObjectLiteralExpression(meta)) return null;

  const property = (name) =>
    meta.properties.find(
      (p) =>
        ts.isPropertyAssignment(p) &&
        (ts.isIdentifier(p.name) || ts.isStringLiteral(p.name)) &&
        p.name.text === name,
    )?.initializer;
  const title = property('title');
  const component = property('component');
  const tags = property('tags');

  const designParameters = [];
  let figmaUrlLiterals = 0;
  const visit = (node) => {
    if (
      ts.isCallExpression(node) &&
      ts.isIdentifier(node.expression) &&
      node.expression.text === 'designParameters' &&
      node.arguments[0] &&
      ts.isStringLiteralLike(node.arguments[0])
    ) {
      designParameters.push(node.arguments[0].text);
    }
    if (ts.isStringLiteralLike(node) && FIGMA_URL_IN_TEXT.test(node.text)) figmaUrlLiterals++;
    ts.forEachChild(node, visit);
  };
  visit(file);

  return {
    title: title && ts.isStringLiteralLike(title) ? title.text : null,
    component: component && ts.isIdentifier(component) ? component.text : null,
    tags:
      tags && ts.isArrayLiteralExpression(tags)
        ? tags.elements.filter(ts.isStringLiteralLike).map((t) => t.text)
        : [],
    firstStory: exported[0] ?? null,
    designParameters,
    figmaUrlLiterals,
  };
}

// ── Links ────────────────────────────────────────────────────────────────────
/**
 * Every component whose figmaUrl is a Figma node, with its story and source,
 * plus every way the single source is broken or bypassed.
 *
 * @param {{ manifest: object, stories: Array<{ path: string, source: string }>, config: { repository: string, branch: string, storybookUrl: string|null }, packageName: string }} input
 * @returns {{ links: object[], problems: string[], total: number }}
 */
export function collectDesignLinks({ manifest, stories, config, packageName }) {
  const specs = manifest.componentSpecs ?? {};
  const names = Object.keys(specs).sort();
  const metas = stories
    .map((story) => ({ ...story, meta: readStoryMeta(story.source) }))
    .filter((story) => story.meta)
    .sort((a, b) => a.path.localeCompare(b.path));
  const repository = config.repository.replace(/\/+$/, '');
  const blob = (path) => `${repository}/blob/${config.branch}/${path}`;
  const storybook = config.storybookUrl ? config.storybookUrl.replace(/\/+$/, '') : null;

  const links = [];
  const problems = [];
  for (const name of names) {
    const spec = specs[name];
    if (spec?.figmaUrl == null) continue;
    const node = parseFigmaNodeUrl(spec.figmaUrl);
    if (!node) {
      problems.push(
        `${name}: figmaUrl is not a Figma node URL (…/design/<file>/<name>?node-id=<x>-<y>): ${spec.figmaUrl}`,
      );
      continue;
    }
    const story = metas.find((s) => s.meta.component === name);
    if (!story) {
      problems.push(`${name}: has a Figma node but no story file whose meta component is ${name}.`);
    } else if (!story.meta.designParameters.includes(name)) {
      problems.push(
        `${story.path}: spread designParameters('${name}') into the meta parameters, so Storybook's Design tab shows the Figma node from the manifest.`,
      );
    }
    let storyLink = null;
    if (story) {
      const autodocs = story.meta.tags.includes('autodocs') || !story.meta.firstStory;
      const id = autodocs
        ? storyDocsId(story.meta.title ?? '')
        : `${sanitize(story.meta.title ?? '')}--${sanitize(storyNameFromExport(story.meta.firstStory))}`;
      storyLink = {
        path: story.path,
        id,
        url: storybook
          ? `${storybook}/?path=/${autodocs ? 'docs' : 'story'}/${id}`
          : blob(story.path),
      };
    }
    links.push({
      name,
      figmaUrl: spec.figmaUrl,
      fileKey: node.fileKey,
      nodeId: node.nodeId,
      importLine: `import { ${name} } from '${packageName}';`,
      description: spec.description ?? '',
      source: { path: spec.filePath, url: blob(spec.filePath) },
      story: storyLink,
    });
  }

  for (const story of metas) {
    if (story.meta.figmaUrlLiterals > 0) {
      problems.push(
        `${story.path}: hardcodes a Figma URL. Set the @figma JSDoc tag on the component and use designParameters() instead.`,
      );
    }
    for (const name of story.meta.designParameters) {
      if (!(name in specs)) {
        problems.push(
          `${story.path}: designParameters('${name}') names no component in public/hds-manifest.json.`,
        );
      }
    }
  }
  return { links, problems: problems.sort(), total: names.length };
}

// ── README ───────────────────────────────────────────────────────────────────
const fileName = (path) => path.split('/').at(-1);

/**
 * The README section, as unformatted Markdown (the CLI runs Prettier on it).
 *
 * @param {{ links: object[], total: number }} collected
 */
export function renderReadmeSection({ links, total }) {
  const lines = [
    DESIGN_LINKS_START,
    '',
    '## Design ↔ Code links',
    '',
    'Each component has one Figma source: `figmaUrl` in `public/hds-manifest.json`, which `pnpm manifest:generate` sets from the `@figma` tag in the component JSDoc. `pnpm figma:links` projects it into this table, into Storybook (`parameters.design`), and into the Figma file as dev resources and component descriptions. Runbook: [`figma/README.md`](figma/README.md).',
    '',
    `**${links.length} of ${total}** components link a Figma node.`,
  ];
  if (links.length > 0) {
    lines.push('', '| Component | Figma node | Story | Source |', '| --- | --- | --- | --- |');
    for (const link of links) {
      const story = link.story ? `[${fileName(link.story.path)}](${link.story.path})` : '—';
      lines.push(
        `| \`${link.name}\` | [${link.nodeId}](${link.figmaUrl}) | ${story} | [${fileName(link.source.path)}](${link.source.path}) |`,
      );
    }
  }
  lines.push('', DESIGN_LINKS_END, '');
  return lines.join('\n');
}

/** Replaces the marked section, or inserts it before "## Visual direction" (else at the end). */
export function upsertReadmeSection(readme, section) {
  const body = section.trimEnd();
  const start = readme.indexOf(START_PREFIX);
  const end = readme.indexOf(DESIGN_LINKS_END);
  if (start !== -1 && end > start) {
    return readme.slice(0, start) + body + readme.slice(end + DESIGN_LINKS_END.length);
  }
  const anchor = readme.indexOf(README_ANCHOR);
  if (anchor !== -1) {
    return `${readme.slice(0, anchor + 1)}${body}\n\n${readme.slice(anchor + 1)}`;
  }
  return `${readme.trimEnd()}\n\n${body}\n`;
}

// ── Figma dev resources (REST) ───────────────────────────────────────────────
/**
 * What to create and update so each linked node carries an "HDS source" and an
 * "HDS story" dev resource. A URL already on the node counts as present, under
 * any name (Figma refuses a second resource with the same URL). Nothing is
 * ever deleted.
 *
 * @param {object[]} links     collectDesignLinks().links
 * @param {object[]} existing  DevResource objects from GET /v1/files/:key/dev_resources
 */
export function planDevResources(links, existing) {
  const plan = { create: [], update: [], unchanged: [] };
  for (const link of links) {
    const onNode = existing.filter((r) => r.file_key === link.fileKey && r.node_id === link.nodeId);
    const desired = [{ name: DEV_RESOURCE_NAMES.source, url: link.source.url }];
    if (link.story) desired.push({ name: DEV_RESOURCE_NAMES.story, url: link.story.url });
    for (const want of desired) {
      const same = onNode.find((r) => r.url === want.url);
      if (same) {
        plan.unchanged.push({ component: link.name, name: want.name, id: same.id, url: want.url });
        continue;
      }
      const named = onNode.find((r) => r.name === want.name);
      if (named) {
        plan.update.push({ component: link.name, id: named.id, name: want.name, url: want.url });
      } else {
        plan.create.push({
          component: link.name,
          name: want.name,
          url: want.url,
          file_key: link.fileKey,
          node_id: link.nodeId,
        });
      }
    }
  }
  return plan;
}

const TOKEN_HELP =
  'It needs the file_dev_resources:read and file_dev_resources:write scopes: create a personal access token at https://www.figma.com/settings (Security → Personal access tokens), then pass it for one run only, never in a committed file: FIGMA_ACCESS_TOKEN=<token> pnpm figma:links --dev-resources --dry-run';

function explainStatus(status, method, path, body) {
  if (status === 401 || status === 403) {
    return `Figma refused FIGMA_ACCESS_TOKEN (HTTP ${status}) on ${method} ${path}. The token needs the file_dev_resources:write scope and edit access to the file, or it is expired or revoked. ${TOKEN_HELP}`;
  }
  if (status === 404) {
    return `Figma found no such file (HTTP 404) on ${method} ${path}. Check the @figma URL in the component JSDoc: dev resources need the key of a main file, not a branch.`;
  }
  if (status === 429) {
    return `Figma rate-limited ${method} ${path} (HTTP 429). Wait a minute and run the command again; it only writes what is still missing.`;
  }
  return `Figma API error HTTP ${status} on ${method} ${path}: ${String(body).slice(0, 300)}`;
}

/**
 * Reads the dev resources on every linked node, then creates and updates what
 * planDevResources says. Needs a token; never called by tests with a real one.
 *
 * @param {{ links: object[], token: string|undefined, fetchImpl?: typeof fetch, dryRun?: boolean, baseUrl?: string }} options
 * @returns {Promise<{ plan: object, errors: string[], line: string }>}
 */
export async function syncDevResources({
  links,
  token,
  fetchImpl = globalThis.fetch,
  dryRun = false,
  baseUrl = 'https://api.figma.com',
}) {
  if (!token) {
    throw new Error(
      `FIGMA_ACCESS_TOKEN is not set. pnpm figma:links --dev-resources writes Figma dev resources through the REST API. ${TOKEN_HELP}`,
    );
  }
  const call = async (method, path, payload) => {
    const response = await fetchImpl(`${baseUrl}${path}`, {
      method,
      headers: {
        'X-Figma-Token': token,
        ...(payload ? { 'Content-Type': 'application/json' } : {}),
      },
      ...(payload ? { body: JSON.stringify(payload) } : {}),
    });
    const text = await response.text();
    if (!response.ok) throw new Error(explainStatus(response.status, method, path, text));
    return text ? JSON.parse(text) : {};
  };

  const nodesByFile = new Map();
  for (const link of links) {
    if (!nodesByFile.has(link.fileKey)) nodesByFile.set(link.fileKey, []);
    nodesByFile.get(link.fileKey).push(link.nodeId);
  }
  const existing = [];
  for (const [fileKey, nodeIds] of nodesByFile) {
    const query = encodeURIComponent([...new Set(nodeIds)].join(','));
    const result = await call('GET', `/v1/files/${fileKey}/dev_resources?node_ids=${query}`);
    existing.push(...(result.dev_resources ?? []));
  }

  const plan = planDevResources(links, existing);
  const errors = [];
  const strip = ({ component: _component, ...resource }) => resource;
  if (!dryRun && plan.create.length > 0) {
    const result = await call('POST', '/v1/dev_resources', {
      dev_resources: plan.create.map(strip),
    });
    for (const e of result.errors ?? [])
      errors.push(`${e.node_id ?? e.file_key ?? '?'}: ${e.error}`);
  }
  if (!dryRun && plan.update.length > 0) {
    const result = await call('PUT', '/v1/dev_resources', {
      dev_resources: plan.update.map(strip),
    });
    for (const e of result.errors ?? []) errors.push(`${e.id ?? '?'}: ${e.error}`);
  }
  const line = `dev resources${dryRun ? ' (dry run)' : ''}: created ${plan.create.length} · updated ${plan.update.length} · unchanged ${plan.unchanged.length}`;
  return { plan, errors, line };
}

// ── Figma component descriptions (Plugin API) ────────────────────────────────
const describeComponent = (link) =>
  [
    link.importLine,
    link.description,
    `Source: ${link.source.path}. Generated from public/hds-manifest.json by pnpm figma:links; edit the component JSDoc, not this text.`,
  ]
    .filter(Boolean)
    .join('\n\n');

const DESCRIPTIONS_BODY = `if (hdsChecksum(JSON.stringify(PAYLOAD)) !== CHECKSUM) {
  throw new Error('The descriptions payload does not match its checksum: it changed after pnpm figma:links generated it. Nothing was written. Regenerate with pnpm figma:links and run the script unmodified.');
}
const report = { file: figma.root.name, dryRun: PAYLOAD.dryRun, updated: [], unchanged: [], notFound: [], notComponent: [] };
for (const item of PAYLOAD.items) {
  const node = await figma.getNodeByIdAsync(item.nodeId);
  if (!node) {
    report.notFound.push(item.component + ': node ' + item.nodeId);
    continue;
  }
  if (node.type !== 'COMPONENT' && node.type !== 'COMPONENT_SET') {
    report.notComponent.push(item.component + ': node ' + item.nodeId + ' is a ' + node.type);
    continue;
  }
  const links = (node.documentationLinks || []).map((link) => link.uri);
  if (node.description === item.description && links.length === 1 && links[0] === item.documentationLink) {
    report.unchanged.push(item.component);
    continue;
  }
  report.updated.push({ component: item.component, node: node.name, previousDescription: node.description, previousLinks: links });
  if (!PAYLOAD.dryRun) {
    node.description = item.description;
    node.documentationLinks = [{ uri: item.documentationLink }];
  }
}
return report;`;

/**
 * A use_figma script that sets each linked component's description (import
 * line, JSDoc description, source path) and documentation link (the story),
 * for the components of one Figma file. Idempotent; a dry run writes nothing.
 *
 * @param {object[]} links
 * @param {string} fileKey
 * @param {{ dryRun?: boolean }} [options]
 */
export function buildDescriptionsScript(links, fileKey, { dryRun = false } = {}) {
  const payload = {
    dryRun,
    items: links
      .filter((link) => link.fileKey === fileKey)
      .map((link) => ({
        component: link.name,
        nodeId: link.nodeId,
        description: describeComponent(link),
        documentationLink: (link.story ?? link.source).url,
      })),
  };
  return [
    `// HDS figma:links — component descriptions for Figma file ${fileKey}${dryRun ? ' (dry run: writes nothing)' : ''}.`,
    '// Generated by `pnpm figma:links`. Run it unmodified through use_figma, in that file only.',
    `const PAYLOAD = ${JSON.stringify(payload)};`,
    `const CHECKSUM = '${hdsChecksum(JSON.stringify(payload))}';`,
    hdsChecksum.toString(),
    DESCRIPTIONS_BODY,
    '',
  ].join('\n');
}
