/**
 * scripts/upgrade/schema.mjs (hds#447): the zod source of upgrade/schema.json,
 * the shape of a release ledger (upgrade/releases/<version>.json), of
 * upgrade/index.json (generated by hds#451) and of a release snapshot
 * (docs/api/releases/<version>.json).
 */
import { describe, it, expect, afterEach } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { formatJson } from '../upgrade/format.mjs';
import {
  IMPACTS,
  Index,
  Release,
  STEP_KINDS,
  Snapshot,
  buildJsonSchema,
  checkReleaseDir,
} from '../upgrade/schema.mjs';

const REPO = resolve(fileURLToPath(import.meta.url), '../../..');
const CLI = join(REPO, 'scripts/upgrade/schema.mjs');

const temps = [];
afterEach(() => {
  while (temps.length) rmSync(temps.pop(), { recursive: true, force: true });
});
const tempDir = () => {
  const dir = mkdtempSync(join(tmpdir(), 'hds-ledger-'));
  temps.push(dir);
  return dir;
};

const ROOT = '@hirobius/design-system';

function validLedger() {
  return {
    version: '0.20.0',
    date: '2026-10-01',
    bump: 'minor',
    summary: 'Pattern components move to /patterns and deprecated names are removed.',
    backfilled: true,
    steps: [
      {
        id: '0.20.0/moved/Page',
        kind: 'moved',
        impact: 'breaking',
        plain:
          'Import Page from @hirobius/design-system/patterns, because the package root no longer exports it.',
        auto: { codemod: 'hds-patterns-subpath', args: [] },
        detect: { imports: [{ from: ROOT, names: ['Page'] }] },
        facts: ['moved:.:Page'],
        source: 'docs/api/releases/0.19.1.json..0.20.0.json',
      },
      {
        id: '0.20.0/deprecated/StatusDot',
        kind: 'deprecated',
        impact: 'none',
        plain: 'StatusDot still works but is deprecated; use Badge with dot instead.',
        removeIn: '0.21.0',
        detect: { imports: [{ from: ROOT, names: ['StatusDot'] }], jsx: ['StatusDot'] },
        backfilled: true,
        source: 'CHANGELOG.md:68',
      },
      {
        id: '0.20.0/dependency/@radix-ui/react-toggle',
        kind: 'dependency',
        impact: 'breaking',
        plain:
          'HDS no longer installs @radix-ui/react-toggle, so add it to your own dependencies if your code imports it.',
        range: '^1.1.13',
        detect: { bareImports: ['@radix-ui/react-toggle'], regex: ['react-toggle[\'"]'] },
        facts: ['dependency-removed:@radix-ui/react-toggle'],
        source: 'docs/api/releases/0.19.1.json..0.20.0.json',
      },
    ],
  };
}

/** The ledger with one change applied to a copy. */
function broken(change) {
  const ledger = validLedger();
  change(ledger);
  return ledger;
}

describe('Release (a ledger)', () => {
  it('accepts a well-formed ledger', () => {
    const result = Release.safeParse(validLedger());
    expect(result.error?.issues ?? []).toEqual([]);
  });

  // Each malformed ledger names the field at fault.
  const cases = {
    'a summary over 140 characters': ['summary', (l) => (l.summary = `${'x'.repeat(140)}.`)],
    'a step whose id names another kind': [
      'steps.0.id',
      (l) => (l.steps[0].id = '0.20.0/removed/Page'),
    ],
    'a step whose id names another version': [
      'steps.0.id',
      (l) => (l.steps[0].id = '0.19.0/moved/Page'),
    ],
    'two steps with one id': ['steps.3.id', (l) => l.steps.push({ ...l.steps[0] })],
    'an unknown impact': ['steps.0.impact', (l) => (l.steps[0].impact = 'major')],
    'an unknown kind': ['steps.0.kind', (l) => (l.steps[0].kind = 'gone')],
    'a plain line of two sentences': [
      'steps.0.plain',
      (l) => (l.steps[0].plain = 'Page moved. Import it from /patterns.'),
    ],
    'a plain line with no full stop': [
      'steps.0.plain',
      (l) => (l.steps[0].plain = 'Page moved to /patterns'),
    ],
    'a plain line over two lines': [
      'steps.0.plain',
      (l) => (l.steps[0].plain = 'Page moved\nto /patterns.'),
    ],
    'an empty detect': ['steps.0.detect', (l) => (l.steps[0].detect = {})],
    'a detect regex that does not compile': [
      'steps.2.detect.regex.0',
      (l) => (l.steps[2].detect.regex = ['(']),
    ],
    'an unknown detect key': ['steps.0.detect', (l) => (l.steps[0].detect.files = ['x'])],
    'a deprecation with no removeIn': ['steps.1.removeIn', (l) => delete l.steps[1].removeIn],
    'a removeIn that is not after the release': [
      'steps.1.removeIn',
      (l) => (l.steps[1].removeIn = '0.20.0'),
    ],
    'an unknown step field': ['steps.0', (l) => (l.steps[0].owner = 'someone')],
    'a codemod that is not a bin name': [
      'steps.0.auto.codemod',
      (l) => (l.steps[0].auto.codemod = 'Hds Prefix'),
    ],
    'a date that is not YYYY-MM-DD': ['date', (l) => (l.date = '1 Oct 2026')],
    'a bump that is not patch, minor or major': ['bump', (l) => (l.bump = 'breaking')],
    'a version that is not semver': ['version', (l) => (l.version = 'v0.20')],
  };
  for (const [name, [path, change]] of Object.entries(cases)) {
    it(`rejects ${name} at ${path}`, () => {
      const result = Release.safeParse(broken(change));
      expect(result.success).toBe(false);
      expect(result.error.issues.map((issue) => issue.path.join('.'))).toContain(path);
    });
  }
});

describe('Index (upgrade/index.json, written by hds#451)', () => {
  const index = {
    package: ROOT,
    latest: '0.20.0',
    floor: '0.16.0',
    versions: [
      {
        version: '0.20.0',
        date: '2026-10-01',
        bump: 'minor',
        breaking: 241,
        summary: 'Pattern components move to /patterns and deprecated names are removed.',
      },
    ],
    deprecated: [
      {
        name: 'StatusDot',
        entry: '.',
        removeIn: '0.21.0',
        useInstead: 'Badge dot',
        step: '0.20.0/deprecated/StatusDot',
      },
    ],
  };

  it('accepts versions, a floor and the deprecated names with removeIn', () => {
    expect(Index.safeParse(index).error?.issues ?? []).toEqual([]);
  });

  it('requires a floor', () => {
    const { floor: _floor, ...rest } = index;
    expect(Index.safeParse(rest).success).toBe(false);
  });

  it('requires removeIn on a deprecated name', () => {
    const { removeIn: _removeIn, ...rest } = index.deprecated[0];
    expect(Index.safeParse({ ...index, deprecated: [rest] }).success).toBe(false);
  });
});

describe('Snapshot', () => {
  it('accepts every committed docs/api/releases/*.json', () => {
    const dir = join(REPO, 'docs/api/releases');
    const files = readdirSync(dir).filter((f) => f.endsWith('.json'));
    expect(files.length).toBeGreaterThanOrEqual(2);
    for (const file of files) {
      const result = Snapshot.safeParse(JSON.parse(readFileSync(join(dir, file), 'utf8')));
      expect(result.error?.issues ?? [], file).toEqual([]);
    }
  });
});

describe('checkReleaseDir', () => {
  it('reports nothing for a directory of valid ledgers', () => {
    const dir = tempDir();
    writeFileSync(join(dir, '0.20.0.json'), formatJson(validLedger()));
    expect(checkReleaseDir(dir)).toEqual([]);
  });

  it('names the file and the field of a malformed ledger', () => {
    const dir = tempDir();
    writeFileSync(join(dir, '0.20.0.json'), formatJson(validLedger()));
    writeFileSync(
      join(dir, '0.19.0.json'),
      formatJson({ ...validLedger(), version: '0.19.0', steps: [{ id: '0.19.0/look/x' }] }),
    );
    const problems = checkReleaseDir(dir);
    expect(problems.length).toBeGreaterThan(0);
    expect(problems.every((p) => p.startsWith('0.19.0.json: '))).toBe(true);
    expect(problems.join('\n')).toMatch(/steps\.0\.kind/);
  });

  it('reports a ledger whose file name is not its version, and a file that is not JSON', () => {
    const dir = tempDir();
    writeFileSync(join(dir, '0.20.1.json'), formatJson(validLedger()));
    writeFileSync(join(dir, '0.20.2.json'), '{ not json');
    const problems = checkReleaseDir(dir);
    expect(problems).toContainEqual(expect.stringMatching(/^0\.20\.1\.json: .*0\.20\.0/));
    expect(problems).toContainEqual(expect.stringMatching(/^0\.20\.2\.json: /));
  });
});

describe('upgrade/schema.json', () => {
  it('is generated from the zod schema, byte for byte', () => {
    const committed = readFileSync(join(REPO, 'upgrade/schema.json'), 'utf8');
    expect(committed).toBe(formatJson(buildJsonSchema()));
  });

  it('describes a release ledger at the root, with the index and snapshot shapes in $defs', () => {
    const schema = buildJsonSchema();
    expect(schema.$ref).toBe('#/$defs/release');
    for (const def of ['release', 'step', 'detect', 'auto', 'index', 'snapshot']) {
      expect(Object.keys(schema.$defs)).toContain(def);
    }
    expect(schema.$defs.step.properties.kind.enum).toEqual(STEP_KINDS);
    expect(schema.$defs.step.properties.impact.enum).toEqual(IMPACTS);
    expect(Object.keys(schema.$defs.detect.properties).sort()).toEqual(
      ['bareImports', 'classes', 'cssVarWrites', 'cssVars', 'imports', 'jsx', 'regex'].sort(),
    );
    expect(schema.$defs.release.properties.summary.maxLength).toBe(140);
  });

  it('--check exits 0 on the committed file and 1 on a hand edit, naming the fix', () => {
    expect(spawnSync(process.execPath, [CLI, '--check'], { encoding: 'utf8' }).status).toBe(0);
    const edited = join(tempDir(), 'schema.json');
    writeFileSync(edited, formatJson({ ...buildJsonSchema(), title: 'edited' }));
    const res = spawnSync(process.execPath, [CLI, '--check', edited], { encoding: 'utf8' });
    expect(res.status).toBe(1);
    expect(res.stderr).toContain('node scripts/upgrade/schema.mjs');
  });

  it('--json reports drift as a violation in the gate-output shape', () => {
    const current = spawnSync(process.execPath, [CLI, '--check', '--json'], { encoding: 'utf8' });
    expect(current.status).toBe(0);
    expect(JSON.parse(current.stdout)).toEqual({ violations: [], ok: true });

    const edited = join(tempDir(), 'schema.json');
    writeFileSync(edited, '{}\n');
    const stale = spawnSync(process.execPath, [CLI, '--check', edited, '--json'], {
      encoding: 'utf8',
    });
    expect(stale.status).toBe(1);
    const { violations, ok } = JSON.parse(stale.stdout);
    expect(ok).toBe(false);
    expect(violations).toEqual([
      expect.objectContaining({
        file: edited,
        line: null,
        rule: 'schema-stale',
        severity: 'error',
      }),
    ]);
  });

  it('runs --check in pretest, so a stale schema.json fails CI', () => {
    const pkg = JSON.parse(readFileSync(join(REPO, 'package.json'), 'utf8'));
    expect(pkg.scripts.pretest).toContain('node scripts/upgrade/schema.mjs --check');
  });
});
